Models/Enums/CellTile.cs
namespace Tanks.Models.Enums
{
	public enum CellTile
	{
		Empty,
		FriendlyBase,
		EnemyBase,
		Brick,
		Bedrock
	}
}

Models/Enums/CellTileExtension.cs
using Tanks.Game.Enums;

namespace Tanks.Models.Enums
{
    public static class CellTileExtension
    {
        private static Dictionary<GameCellTile, CellTile> _convertDictionary =
            new Dictionary<GameCellTile, CellTile>()
            {
                { GameCellTile.Bedrock, CellTile.Bedrock},
                { GameCellTile.FriendlyBase, CellTile.FriendlyBase},
                { GameCellTile.Brick, CellTile.Brick},
                { GameCellTile.EnemyBase, CellTile.EnemyBase},
                { GameCellTile.Empty, CellTile.Empty}
            };

        public static CellTile ToCellTile(this GameCellTile source)
        {
            return _convertDictionary[source];
        }
    }
}

Models/ErrorViewModel.cs
namespace Tanks.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/GameFieldCellModel.cs
namespace Tanks.Models
{
	public class GameFieldCellModel
	{
	}
}

Models/GameFieldModel.cs
using Tanks.Game.Enums;
using Tanks.Game.Interfaces;
using Tanks.Models.Enums;

namespace Tanks.Models
{
    public class GameFieldModel
    {
        public int FieldWidth { get; private set; }
        public int FieldHeight { get; private set; }

        public CellTile[][] Map { get; private set; }

        public GameFieldModel(IGameTanks game)
        {
            FieldHeight = game.GameField.FieldHeight;
            FieldWidth = game.GameField.FieldWidth;

            Map = game.GameField.Map.Select(x => 
            x.Select(y => y.ToCellTile()).ToArray()
            ).ToArray();
        }
    }
}

Models/GameFightFieldModel.cs
using Tanks.Game.Interfaces;

namespace Tanks.Models
{
    public class GameFightFieldModel
    {
        private IGameTanks game;

        public GameFightFieldModel(IGameTanks game)
        {
            
        }
    }
}

Models/GameModel.cs
using Tanks.Game.Interfaces;

namespace Tanks.Models
{
	public class GameModel
	{
		public GameFieldModel GameFieldModel { get; private set; }
		public GameFightFieldModel GameFightFieldModel { get; private set; }
		public GameModel(IGameTanks game)
		{
			GameFieldModel = new GameFieldModel(game);
			GameFightFieldModel = new GameFightFieldModel(game);
		}
	}
}

Controllers/ApiController.cs
using Microsoft.AspNetCore.Mvc;
using Tanks.Game.Interfaces;
using Tanks.Models;

namespace Tanks.Controllers
{
    public class ApiController: Controller
    {
        private readonly IProfile _profile;
        private readonly IGameManager _gameManager;
        public ApiController(IProfile profile, IGameManager gameManager) 
        {
            this._profile = profile;
            this._gameManager = gameManager;
        }
        public IActionResult Login(string login, string pass)
        {
            if (login == null || pass == null) return new JsonResult("Failure"); ;
            if (_profile.ValidateProfile(login, pass)) 
            {
                return new RedirectToActionResult("Game", "Game", null); ;
            }
            return new JsonResult("Failure");
        }

        [HttpPost]
        [Route(nameof(StartGame))]
        public IActionResult StartGame()
        {
            var gameTanks = _gameManager.GetGameTanks(null);
            gameTanks.StartGame();
            var gameModel = new GameModel(gameTanks);

            return PartialView("GameField", gameModel.GameFieldModel);
        }
    }
}

Controllers/GameApiController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Tanks.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class GameApiController : ControllerBase
    {
        [HttpPost]
        [Route("move")]
        public void Move()
        {
            
        }
        [HttpPost]
        [Route("attack")]
        public void Attack()
        {

        }
        [HttpPost]
        [Route("die")]
        public void Die()
        {

        }
        [HttpPost]
        [Route("pay")]
        public void Pay()
        {

        }
        [HttpPost]
        [Route("restore")]
        public void Restore ()
        {

        }
        [HttpGet]
        [Route("getCurrentPosition")]
        public string GetCurrentPosition()
        {
            return string.Empty;
        }
    }
}

Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using Tanks.Game.Interfaces;
using Tanks.Models;


namespace Tanks.Controllers
{
    public class GameController(IGameManager _gameManager) : Controller
    {
        public IActionResult Game()
        {
            var game = _gameManager.GetGameTanks(null);
            var dataModel = new GameModel(game);
            return View(dataModel);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Tanks.Models;

namespace Tanks.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Authorization()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Game/Game.cshtml
@model GameModel

@{
    ViewData["Title"] = "Game";
}

@section HeadResources
{
    <link rel="stylesheet" href="~/css/Game.css"></link>
    <script src="/js/Game.js" type="module"></script>
}

<div class="text-center GameContainer">
    @{
        await Html.RenderPartialAsync("GameField", Model.GameFieldModel);
        await Html.RenderPartialAsync("GameFightField", Model.GameFightFieldModel);
    }
    <div class="GameButtons">
        <button id="NewGameButton" type="button">New Game</button>
    </div>
</div>

Views/Home/Authorization.cshtml
@{
    ViewData["Title"] = "Authorization";
}

@section HeadResources
{
    <link rel="stylesheet" href="/css/authorization.css">
}

@section Scripts
{
    <script src='http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js'></script>
    <script src="/js/authorization.js"></script>
}

<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>

<div class="container">
    <div class="frame">
        <div class="nav">
            <ul class="links">
                <li class="signin-active"><a class="btn">Вход</a></li>
                <li class="signup-inactive"><a class="btn">Регистрация</a></li>
            </ul>
        </div>
        <div ng-app ng-init="checked = false">
            <form class="form-signin" asp-controller="Api" asp-action="Login" method="post" name="form">
                <label for="username">Логин</label>
                <input class="form-styling" type="text" name="login">
                <label for="password">Пароль</label>
                <input class="form-styling" type="text" name="pass">
                <button class="btn-signin" type="submit">Войти</button>
            </form>

            <form class="form-signup" action="" method="post" name="form">
                <label for="fullname">Логин</label>
                <input class="form-styling" type="text" name="fullname" placeholder="" />
                <label for="password">Пароль</label>
                <input class="form-styling" type="text" name="password" placeholder="" />
                <label for="confirmpassword">Подтвердите пароль</label>
                <input class="form-styling" type="text" name="confirmpassword" placeholder="" />
                <a ng-click="checked = !checked" class="btn-signup">Зарегистрироваться</a>
            </form>
        </div>
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Приветствуем</h1>
    <p>Игра находится в разработке.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tanks</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tanks.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("HeadResources", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Танки</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Конфиденциальность</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Authorization">Вход</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Танки - Grokes
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>